package com.mobile.aura.constant;

import lombok.Getter;

public enum CommonStatusEnum {
    // 1000-1099
    EMAIL_CODE_INVALID(1000, "EMAIL CODE INVALID"),
    VERIFICATION_CODE_ERROR(1001, "VERIFICATION CODE ERROR"),

    // 1100-1199 Token/JWT
    TOKEN_INVALID(1100, "TOKEN INVALID"),
    TOKEN_EXPIRED(1101, "TOKEN EXPIRED"),
    UNAUTHORIZED(1102, "UNAUTHORIZED"),
    REFRESH_INVALID(1110, "REFRESH TOKEN INVALID"),

    // 1200-1299 user
    USER_NOT_EXISTS(1200, "USER IS NOT EXISTS"),
    BAD_CREDENTIALS(1201, "BAD CREDENTIALS"),
    PHONE_REGISTERED(1202, "PHONE ALREADY REGISTERED"),
    EMAIL_REGISTERED(1203, "EMAIL ALREADY REGISTERED"),
    ACCOUNT_UNVERIFIED(1204, "ACCOUNT NOT VERIFIED"),
    ACCOUNT_DEACTIVATED(1205, "ACCOUNT DEACTIVATED"),

    // 1300-1399 post and interaction
    POST_NOT_FOUND(1300, "POST NOT FOUND"),
    CANNOT_FOLLOW_SELF (1301, "CANNOT FOLLOW SELF"),
    ALREADY_FOLLOWING  (1302, "ALREADY FOLLOWING"),
    NOT_FOLLOWING      (1303, "NOT FOLLOWING"),
    CANNOT_BLOCK_SELF  (1304, "CANNOT BLOCK SELF"),
    USER_BLOCKED       (1305, "USER BLOCKED"),
    YOU_ARE_BLOCKED    (1306, "YOU ARE BLOCKED"),
    RELATION_PRIVATE (1307, "RELATION PRIVATE"),
    BLOCKED_ACCESS   (1308, "BLOCKED"),
    COMMENT_NOT_FOUND(1309, "COMMENT_NOT_FOUND"),
    NOT_BLOCKING       (1310, "NOT BLOCKING"),
    ALREADY_LIKED(1311, "ALREADY LIKED"),
    NOT_LIKED(1312, "NOT LIKED"),
    ALREADY_BOOKMARKED(1313, "ALREADY BOOKMARKED"),
    NOT_BOOKMARKED(1314, "NOT BOOKMARKED"),
    TITLE_REQUIRED(1315, "TITLE REQUIRED"),

    // Common
    INVALID_PARAM(1400, "INVALID PARAM"),
    FORBIDDEN(1403, "FORBIDDEN"),
    NOT_FOUND(1404, "NOT FOUND"),
    NOT_IMPLEMENTED(1405, "NOT IMPLEMENTED"),

    // 1500-1599 system notification
    NOTIFICATION_NOT_FOUND(1500, "NOTIFICATION NOT FOUND"),

    // 1600-1699 meal plan
    FOOD_NOT_FOUND(1600, "FOOD NOT FOUND"),
    MEAL_LOG_NOT_FOUND(1601, "MEAL LOG NOT FOUND"),
    INVALID_MEAL_TYPE(1602, "INVALID MEAL TYPE"),
    FOOD_NAME_DUPLICATE(1603, "FOOD NAME ALREADY EXISTS"),

    // 1700-1799 sport and health
    EXERCISE_NOT_FOUND(1700, "EXERCISE NOT FOUND"),
    EXERCISE_LOG_NOT_FOUND(1701, "EXERCISE LOG NOT FOUND"),
    WEIGHT_NOT_SET(1702, "WEIGHT NOT SET"),
    STEP_RECORD_NOT_FOUND(1703, "STEP RECORD NOT FOUND"),
    STEP_SYNC_CONFLICT(1704, "STEP SYNC CONFLICT"),
    WATER_GOAL_NOT_SET(1705, "WATER GOAL NOT SET"),
    HEALTH_PROFILE_NOT_FOUND(1706, "HEALTH PROFILE NOT FOUND"),
    DATE_RANGE_TOO_LARGE(1707, "DATE RANGE TOO LARGE"),

    // 1800-1899 reset password
    OLD_PASSWORD_WRONG(1800, "OLD PASSWORD WRONG"),
    PASSWORD_WEAK(1801, "PASSWORD TOO WEAK"),
    NEW_PASSWORD_SAME (1802, "NEW PASSWORD SAME AS OLD"),

    // 1900-1999 email
    EMAIL_MISMATCH(1900, "EMAIL NOT MATCH"),
    EMAIL_NOT_BOUND(1901, "EMAIL NOT BOUND"),
    EMAIL_CODE_USED   (1902, "EMAIL CODE USED"),
    EMAIL_CODE_EXPIRED(1903, "EMAIL CODE EXPIRED"),

    // 2000-2099 file upload
    FILE_EMPTY(2000, "FILE IS EMPTY"),
    FILE_TOO_LARGE(2001, "FILE TOO LARGE"),
    FILE_TYPE_UNKNOWN(2002, "FILE TYPE UNKNOWN"),
    FILE_TYPE_NOT_ALLOWED(2003, "FILE TYPE NOT ALLOWED"),
    FILE_UPLOAD_FAILED(2004, "FILE UPLOAD FAILED"),

    // common
    SUCCESS(1, "success"),
    FAIL(0, "fail");



    @Getter private final int code;
    @Getter private final String value;
    CommonStatusEnum(int code, String value){ this.code=code; this.value=value; }
}
